# Generated by Django 4.2.4 on 2023-12-21 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.CharField(max_length=255)),
                ('caller_name', models.CharField(max_length=255)),
                ('callee_id', models.CharField(max_length=255)),
                ('callee_name', models.CharField(max_length=255)),
                ('channel_name', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('call_answered', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.DurationField(blank=True, null=True)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.callsession')),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callee', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
