# Generated by Django 4.2.4 on 2023-12-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnotification',
            name='call_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callee', to='call.callsession'),
        ),
    ]
