# Generated by Django 4.2.4 on 2023-12-27 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_alter_callnotification_call_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnotification',
            name='call_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='call.callsession'),
        ),
    ]
