# Generated by Django 4.2.4 on 2023-12-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_alter_callnotification_call_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='callnotification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
